#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

FILEPATH=$1
IP_ADDRESS=$2
USERNAME=$3
PRIVATE_KEY=$4

if [ $# -eq 4 ]
then
  scp -o StrictHostKeyChecking=no -i "$PRIVATE_KEY" "$FILEPATH" "$USERNAME@$IP_ADDRESS:~/"
else
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
