#!/usr/bin/env bash
# Install nginx with custom 404 page that contains the string
# Ceci n'est pas une page

sudo apt update
sudo apt install -y nginx

sudo sed -i "53s/.*/\t\terror_page 404 \/custom_404.html;\n\t\tlocation \/custom_404.html {\n\t\t\t\troot \/var\/www\/html;\n\t\t\t\tinternal;\n\t\t}/" /etc/nginx/sites-enabled/default

# Create default nginx folder for pages
sudo mkdir -p /var/www/html

sudo touch /var/www/html/custom_404.html

sudo chown -R "$USER":"$USER" /var/www/html/custom_404.html

# Overwite file content
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Restart nginx server
sudo service nginx restart
