#!/usr/bin/env bash
# install and comfigure a load balnacer
# with haproxy and roundrobin config

sudo apt-get -y update
sudo apt-get install -y haproxy

apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo -e "frontend myfrontend
\tbind 0.0.0.0:80
\tdefault_backend myservers

backend web_servers
        balance roundrobin
        server 246056-web-01 107.23.90.175 check
        server 246056-web-02 100.25.21.55 check
' >> /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy

# restart HAproxy service
sudo service haproxy restart
