#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with Requirements
# create a backup host file in home directory
cp /etc/hosts ~/"$(date +%s)hosts.new"

# Add new rules to host file
echo "127.0.0.2	localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
