#!/usr/bin/env bash
# Script to run nginx server under user nginx on port 8080

chmod 644 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-enabled/default
pkill -f apache2
sudo -u nginx service nginx start
